// This file is auto-generated by @hey-api/openapi-ts

export const AIAlgorithmSchema = {
    type: 'string',
    enum: ['random', 'alphabeta', 'montecarlo', 'qlearning'],
    title: 'AIAlgorithm'
} as const;

export const AIConfigSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        algorithm: {
            '$ref': '#/components/schemas/AIAlgorithm'
        },
        parameters: {
            additionalProperties: true,
            type: 'object',
            title: 'Parameters'
        },
        heuristic: {
            '$ref': '#/components/schemas/AIHeuristic',
            default: 'none'
        }
    },
    type: 'object',
    required: ['algorithm', 'parameters'],
    title: 'AIConfig'
} as const;

export const AIHeuristicSchema = {
    type: 'string',
    enum: ['static_weights', 'mobility_based', 'hybrid', 'none'],
    title: 'AIHeuristic'
} as const;

export const AlphaBetaParamsSchema = {
    properties: {
        depth: {
            type: 'integer',
            maximum: 8,
            minimum: 1,
            title: 'Depth',
            description: 'Profundidad del árbol (1-8)'
        },
        use_sorting: {
            type: 'boolean',
            title: 'Use Sorting',
            description: 'Ordenar movimientos para optimizar poda',
            default: true
        },
        time_limit_ms: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Time Limit Ms',
            description: 'Tiempo límite por jugada',
            default: 1000
        }
    },
    type: 'object',
    required: ['depth'],
    title: 'AlphaBetaParams'
} as const;

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: 'password'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const BotMoveResponseSchema = {
    properties: {
        game: {
            '$ref': '#/components/schemas/GamePublic'
        },
        move_made: {
            anyOf: [
                {
                    items: {
                        type: 'integer'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Move Made'
        },
        message: {
            type: 'string',
            title: 'Message'
        },
        execution_time: {
            type: 'number',
            title: 'Execution Time'
        },
        memory_peak_mb: {
            type: 'number',
            title: 'Memory Peak Mb'
        }
    },
    type: 'object',
    required: ['game', 'move_made', 'message', 'execution_time', 'memory_peak_mb'],
    title: 'BotMoveResponse'
} as const;

export const ConfigAlphaBetaSchema = {
    properties: {
        algorithm: {
            type: 'string',
            const: 'alphabeta',
            title: 'Algorithm'
        },
        heuristic: {
            '$ref': '#/components/schemas/AIHeuristic'
        },
        parameters: {
            '$ref': '#/components/schemas/AlphaBetaParams'
        }
    },
    type: 'object',
    required: ['algorithm', 'heuristic', 'parameters'],
    title: 'ConfigAlphaBeta'
} as const;

export const ConfigMonteCarloSchema = {
    properties: {
        algorithm: {
            type: 'string',
            const: 'montecarlo',
            title: 'Algorithm'
        },
        heuristic: {
            '$ref': '#/components/schemas/AIHeuristic'
        },
        parameters: {
            '$ref': '#/components/schemas/MonteCarloParams'
        }
    },
    type: 'object',
    required: ['algorithm', 'heuristic', 'parameters'],
    title: 'ConfigMonteCarlo'
} as const;

export const ConfigQLearningSchema = {
    properties: {
        algorithm: {
            type: 'string',
            const: 'qlearning',
            title: 'Algorithm'
        },
        heuristic: {
            '$ref': '#/components/schemas/AIHeuristic'
        },
        parameters: {
            '$ref': '#/components/schemas/QLearningParams'
        }
    },
    type: 'object',
    required: ['algorithm', 'heuristic', 'parameters'],
    title: 'ConfigQLearning'
} as const;

export const ConfigRandomSchema = {
    properties: {
        algorithm: {
            type: 'string',
            const: 'random',
            title: 'Algorithm'
        },
        heuristic: {
            '$ref': '#/components/schemas/AIHeuristic',
            default: 'none'
        },
        parameters: {
            additionalProperties: true,
            type: 'object',
            title: 'Parameters',
            default: {}
        }
    },
    type: 'object',
    required: ['algorithm'],
    title: 'ConfigRandom'
} as const;

export const GameSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        player_black_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Player Black Id'
        },
        bot_black_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Bot Black Id'
        },
        player_white_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Player White Id'
        },
        bot_white_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Bot White Id'
        },
        simulation_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Simulation Id'
        },
        board_state: {
            items: {},
            type: 'array',
            title: 'Board State'
        },
        score_black: {
            type: 'integer',
            title: 'Score Black',
            default: 2
        },
        score_white: {
            type: 'integer',
            title: 'Score White',
            default: 2
        },
        current_turn: {
            '$ref': '#/components/schemas/Turn',
            default: 'black'
        },
        winner: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/Winner'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: ['owner_id'],
    title: 'Game'
} as const;

export const GameCreateSchema = {
    properties: {
        player_black_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Player Black Id'
        },
        bot_black_config: {
            anyOf: [
                {
                    oneOf: [
                        {
                            '$ref': '#/components/schemas/ConfigAlphaBeta'
                        },
                        {
                            '$ref': '#/components/schemas/ConfigMonteCarlo'
                        },
                        {
                            '$ref': '#/components/schemas/ConfigQLearning'
                        },
                        {
                            '$ref': '#/components/schemas/ConfigRandom'
                        }
                    ],
                    discriminator: {
                        propertyName: 'algorithm',
                        mapping: {
                            alphabeta: '#/components/schemas/ConfigAlphaBeta',
                            montecarlo: '#/components/schemas/ConfigMonteCarlo',
                            qlearning: '#/components/schemas/ConfigQLearning',
                            random: '#/components/schemas/ConfigRandom'
                        }
                    }
                },
                {
                    type: 'null'
                }
            ],
            title: 'Bot Black Config'
        },
        player_white_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Player White Id'
        },
        bot_white_config: {
            anyOf: [
                {
                    oneOf: [
                        {
                            '$ref': '#/components/schemas/ConfigAlphaBeta'
                        },
                        {
                            '$ref': '#/components/schemas/ConfigMonteCarlo'
                        },
                        {
                            '$ref': '#/components/schemas/ConfigQLearning'
                        },
                        {
                            '$ref': '#/components/schemas/ConfigRandom'
                        }
                    ],
                    discriminator: {
                        propertyName: 'algorithm',
                        mapping: {
                            alphabeta: '#/components/schemas/ConfigAlphaBeta',
                            montecarlo: '#/components/schemas/ConfigMonteCarlo',
                            qlearning: '#/components/schemas/ConfigQLearning',
                            random: '#/components/schemas/ConfigRandom'
                        }
                    }
                },
                {
                    type: 'null'
                }
            ],
            title: 'Bot White Config'
        }
    },
    type: 'object',
    title: 'GameCreate'
} as const;

export const GamePublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        board_state: {
            items: {},
            type: 'array',
            title: 'Board State'
        },
        score_black: {
            type: 'integer',
            title: 'Score Black'
        },
        score_white: {
            type: 'integer',
            title: 'Score White'
        },
        current_turn: {
            '$ref': '#/components/schemas/Turn'
        },
        winner: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/Winner'
                },
                {
                    type: 'null'
                }
            ]
        },
        player_black: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/UserPublic'
                },
                {
                    type: 'null'
                }
            ]
        },
        player_white: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/UserPublic'
                },
                {
                    type: 'null'
                }
            ]
        },
        bot_black_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Bot Black Id'
        },
        bot_white_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Bot White Id'
        }
    },
    type: 'object',
    required: ['id', 'owner_id', 'board_state', 'score_black', 'score_white', 'current_turn', 'winner', 'player_black', 'player_white', 'bot_black_id', 'bot_white_id'],
    title: 'GamePublic'
} as const;

export const GameStatsSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        move_count: {
            type: 'integer',
            title: 'Move Count'
        },
        winner: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Winner'
        },
        score_black: {
            type: 'integer',
            title: 'Score Black'
        },
        score_white: {
            type: 'integer',
            title: 'Score White'
        },
        avg_time_black: {
            type: 'number',
            title: 'Avg Time Black'
        },
        avg_ram_black: {
            type: 'number',
            title: 'Avg Ram Black'
        },
        avg_time_white: {
            type: 'number',
            title: 'Avg Time White'
        },
        avg_ram_white: {
            type: 'number',
            title: 'Avg Ram White'
        }
    },
    type: 'object',
    required: ['id', 'move_count', 'winner', 'score_black', 'score_white', 'avg_time_black', 'avg_ram_black', 'avg_time_white', 'avg_ram_white'],
    title: 'GameStats'
} as const;

export const GamesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/Game'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'GamesPublic'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const MonteCarloParamsSchema = {
    properties: {
        iterations: {
            type: 'integer',
            maximum: 10000,
            minimum: 10,
            title: 'Iterations',
            description: 'Número de simulaciones'
        },
        exploration_constant: {
            type: 'number',
            title: 'Exploration Constant',
            description: 'Constante C de exploración',
            default: 1.41
        },
        time_limit: {
            type: 'number',
            maximum: 120,
            minimum: 0.1,
            title: 'Time Limit',
            description: 'Tiempo límite en segundos',
            default: 4.5
        }
    },
    type: 'object',
    required: ['iterations'],
    title: 'MonteCarloParams'
} as const;

export const MoveCreateSchema = {
    properties: {
        coordinate: {
            items: {
                type: 'integer'
            },
            type: 'array',
            title: 'Coordinate'
        }
    },
    type: 'object',
    required: ['coordinate'],
    title: 'MoveCreate'
} as const;

export const MovesSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        game_id: {
            type: 'string',
            format: 'uuid',
            title: 'Game Id'
        },
        move_number: {
            type: 'integer',
            title: 'Move Number'
        },
        player: {
            '$ref': '#/components/schemas/Turn'
        },
        position: {
            anyOf: [
                {
                    items: {},
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Position'
        },
        execution_time: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Execution Time'
        },
        memory_used: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Memory Used'
        }
    },
    type: 'object',
    required: ['game_id', 'move_number', 'player'],
    title: 'Moves'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const QLearningParamsSchema = {
    properties: {
        learning_rate: {
            type: 'number',
            maximum: 1,
            minimum: 0,
            title: 'Learning Rate',
            default: 0.1
        },
        discount_factor: {
            type: 'number',
            maximum: 1,
            minimum: 0,
            title: 'Discount Factor',
            default: 0.9
        },
        epsilon: {
            type: 'number',
            maximum: 1,
            minimum: 0,
            title: 'Epsilon',
            description: 'Probabilidad de exploración',
            default: 0.1
        }
    },
    type: 'object',
    title: 'QLearningParams'
} as const;

export const SimulationSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            type: 'number',
            title: 'Created At'
        },
        num_games: {
            type: 'integer',
            title: 'Num Games'
        },
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        bot_black_id: {
            type: 'string',
            format: 'uuid',
            title: 'Bot Black Id'
        },
        bot_white_id: {
            type: 'string',
            format: 'uuid',
            title: 'Bot White Id'
        },
        black_wins: {
            type: 'integer',
            title: 'Black Wins'
        },
        white_wins: {
            type: 'integer',
            title: 'White Wins'
        },
        draws: {
            type: 'integer',
            title: 'Draws'
        },
        time_elapsed: {
            type: 'number',
            title: 'Time Elapsed'
        }
    },
    type: 'object',
    required: ['num_games', 'user_id', 'bot_black_id', 'bot_white_id', 'black_wins', 'white_wins', 'draws', 'time_elapsed'],
    title: 'Simulation'
} as const;

export const SimulationDetailsSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            type: 'number',
            title: 'Created At'
        },
        num_games: {
            type: 'integer',
            title: 'Num Games'
        },
        time_elapsed: {
            type: 'number',
            title: 'Time Elapsed'
        },
        bot_black: {
            '$ref': '#/components/schemas/AIConfig'
        },
        bot_white: {
            '$ref': '#/components/schemas/AIConfig'
        },
        black_wins: {
            type: 'integer',
            title: 'Black Wins'
        },
        white_wins: {
            type: 'integer',
            title: 'White Wins'
        },
        draws: {
            type: 'integer',
            title: 'Draws'
        },
        global_avg_time_black: {
            type: 'number',
            title: 'Global Avg Time Black'
        },
        global_avg_ram_black: {
            type: 'number',
            title: 'Global Avg Ram Black'
        },
        global_avg_time_white: {
            type: 'number',
            title: 'Global Avg Time White'
        },
        global_avg_ram_white: {
            type: 'number',
            title: 'Global Avg Ram White'
        },
        games: {
            items: {
                '$ref': '#/components/schemas/GameStats'
            },
            type: 'array',
            title: 'Games'
        }
    },
    type: 'object',
    required: ['id', 'created_at', 'num_games', 'time_elapsed', 'bot_black', 'bot_white', 'black_wins', 'white_wins', 'draws', 'global_avg_time_black', 'global_avg_ram_black', 'global_avg_time_white', 'global_avg_ram_white', 'games'],
    title: 'SimulationDetails'
} as const;

export const SimulationPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            type: 'number',
            title: 'Created At'
        },
        num_games: {
            type: 'integer',
            title: 'Num Games'
        },
        black_wins: {
            type: 'integer',
            title: 'Black Wins'
        },
        white_wins: {
            type: 'integer',
            title: 'White Wins'
        },
        draws: {
            type: 'integer',
            title: 'Draws'
        },
        time_elapsed: {
            type: 'number',
            title: 'Time Elapsed'
        },
        bot_black: {
            '$ref': '#/components/schemas/AIConfig'
        },
        bot_white: {
            '$ref': '#/components/schemas/AIConfig'
        }
    },
    type: 'object',
    required: ['id', 'created_at', 'num_games', 'black_wins', 'white_wins', 'draws', 'time_elapsed', 'bot_black', 'bot_white'],
    title: 'SimulationPublic'
} as const;

export const SimulationRequestSchema = {
    properties: {
        num_games: {
            type: 'integer',
            maximum: 1000,
            minimum: 1,
            title: 'Num Games',
            default: 100
        },
        bot_black: {
            oneOf: [
                {
                    '$ref': '#/components/schemas/ConfigAlphaBeta'
                },
                {
                    '$ref': '#/components/schemas/ConfigMonteCarlo'
                },
                {
                    '$ref': '#/components/schemas/ConfigQLearning'
                },
                {
                    '$ref': '#/components/schemas/ConfigRandom'
                }
            ],
            title: 'Bot Black',
            discriminator: {
                propertyName: 'algorithm',
                mapping: {
                    alphabeta: '#/components/schemas/ConfigAlphaBeta',
                    montecarlo: '#/components/schemas/ConfigMonteCarlo',
                    qlearning: '#/components/schemas/ConfigQLearning',
                    random: '#/components/schemas/ConfigRandom'
                }
            }
        },
        bot_white: {
            oneOf: [
                {
                    '$ref': '#/components/schemas/ConfigAlphaBeta'
                },
                {
                    '$ref': '#/components/schemas/ConfigMonteCarlo'
                },
                {
                    '$ref': '#/components/schemas/ConfigQLearning'
                },
                {
                    '$ref': '#/components/schemas/ConfigRandom'
                }
            ],
            title: 'Bot White',
            discriminator: {
                propertyName: 'algorithm',
                mapping: {
                    alphabeta: '#/components/schemas/ConfigAlphaBeta',
                    montecarlo: '#/components/schemas/ConfigMonteCarlo',
                    qlearning: '#/components/schemas/ConfigQLearning',
                    random: '#/components/schemas/ConfigRandom'
                }
            }
        }
    },
    type: 'object',
    required: ['bot_black', 'bot_white'],
    title: 'SimulationRequest'
} as const;

export const SimulationsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/SimulationPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'SimulationsPublic'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const TurnSchema = {
    type: 'string',
    enum: ['black', 'white'],
    title: 'Turn'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidMovesResponseSchema = {
    properties: {
        game_id: {
            type: 'string',
            format: 'uuid',
            title: 'Game Id'
        },
        current_turn: {
            '$ref': '#/components/schemas/Turn'
        },
        valid_moves: {
            items: {
                items: {
                    type: 'integer'
                },
                type: 'array'
            },
            type: 'array',
            title: 'Valid Moves'
        }
    },
    type: 'object',
    required: ['game_id', 'current_turn', 'valid_moves'],
    title: 'ValidMovesResponse'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;

export const WinnerSchema = {
    type: 'string',
    enum: ['black', 'white', 'draw'],
    title: 'Winner'
} as const;