// This file is auto-generated by @hey-api/openapi-ts

export type AIAlgorithm = 'random' | 'alphabeta' | 'montecarlo' | 'qlearning';

export type AIConfig = {
    id?: string;
    algorithm: AIAlgorithm;
    parameters: {
        [key: string]: unknown;
    };
    heuristic?: AIHeuristic;
};

export type AIHeuristic = 'static_weights' | 'mobility_based' | 'hybrid' | 'none';

export type AlphaBetaParams = {
    /**
     * Profundidad del árbol (1-8)
     */
    depth: number;
    /**
     * Ordenar movimientos para optimizar poda
     */
    use_sorting?: boolean;
    /**
     * Tiempo límite por jugada
     */
    time_limit_ms?: (number | null);
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type BotMoveResponse = {
    game: GamePublic;
    move_made: (Array<(number)> | null);
    message: string;
};

export type ConfigAlphaBeta = {
    algorithm: "alphabeta";
    heuristic: AIHeuristic;
    parameters: AlphaBetaParams;
};

export type ConfigMonteCarlo = {
    algorithm: "montecarlo";
    heuristic: AIHeuristic;
    parameters: MonteCarloParams;
};

export type ConfigQLearning = {
    algorithm: "qlearning";
    heuristic: AIHeuristic;
    parameters: QLearningParams;
};

export type ConfigRandom = {
    algorithm: "random";
    heuristic?: AIHeuristic;
    parameters?: {
        [key: string]: unknown;
    };
};

export type Game = {
    id?: string;
    owner_id: string;
    player_black_id?: (string | null);
    bot_black_id?: (string | null);
    player_white_id?: (string | null);
    bot_white_id?: (string | null);
    board_state?: Array<unknown>;
    score_black?: number;
    score_white?: number;
    current_turn?: Turn;
    winner?: (Winner | null);
};

export type GameCreate = {
    player_black_id?: (string | null);
    bot_black_config?: ((ConfigAlphaBeta | ConfigMonteCarlo | ConfigQLearning | ConfigRandom) | null);
    player_white_id?: (string | null);
    bot_white_config?: ((ConfigAlphaBeta | ConfigMonteCarlo | ConfigQLearning | ConfigRandom) | null);
};

export type GamePublic = {
    id: string;
    owner_id: string;
    board_state: Array<unknown>;
    score_black: number;
    score_white: number;
    current_turn: Turn;
    winner: (Winner | null);
    player_black: (UserPublic | null);
    player_white: (UserPublic | null);
    bot_black_id: (string | null);
    bot_white_id: (string | null);
};

export type GamesPublic = {
    data: Array<Game>;
    count: number;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type Message = {
    message: string;
};

export type MonteCarloParams = {
    /**
     * Número de simulaciones
     */
    iterations: number;
    /**
     * Constante C de exploración
     */
    exploration_constant?: number;
    /**
     * Tiempo límite en segundos
     */
    time_limit?: number;
};

export type MoveCreate = {
    coordinate: Array<(number)>;
};

export type Moves = {
    id?: string;
    game_id: string;
    move_number: number;
    player: Turn;
    position?: (Array<unknown> | null);
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type QLearningParams = {
    learning_rate?: number;
    discount_factor?: number;
    /**
     * Probabilidad de exploración
     */
    epsilon?: number;
};

export type Simulation = {
    id?: string;
    created_at?: number;
    num_games: number;
    user_id: string;
    bot_black_id: string;
    bot_white_id: string;
    black_wins: number;
    white_wins: number;
    draws: number;
    time_elapsed: number;
};

export type SimulationPublic = {
    id: string;
    created_at: number;
    num_games: number;
    black_wins: number;
    white_wins: number;
    draws: number;
    time_elapsed: number;
    bot_black: AIConfig;
    bot_white: AIConfig;
};

export type SimulationRequest = {
    num_games?: number;
    bot_black: (ConfigAlphaBeta | ConfigMonteCarlo | ConfigQLearning | ConfigRandom);
    bot_white: (ConfigAlphaBeta | ConfigMonteCarlo | ConfigQLearning | ConfigRandom);
};

export type SimulationsPublic = {
    data: Array<SimulationPublic>;
    count: number;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type Turn = 'black' | 'white';

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type ValidMovesResponse = {
    game_id: string;
    current_turn: Turn;
    valid_moves: Array<Array<(number)>>;
};

export type Winner = 'black' | 'white' | 'draw';

export type GamesReadGamesData = {
    limit?: number;
    skip?: number;
};

export type GamesReadGamesResponse = (GamesPublic);

export type GamesCreateGameData = {
    requestBody: GameCreate;
};

export type GamesCreateGameResponse = (Game);

export type GamesReadMyGamesData = {
    limit?: number;
    skip?: number;
};

export type GamesReadMyGamesResponse = (GamesPublic);

export type GamesGetGameByIdData = {
    gameId: string;
};

export type GamesGetGameByIdResponse = (Game);

export type GamesGetValidMovesData = {
    gameId: string;
};

export type GamesGetValidMovesResponse = (ValidMovesResponse);

export type GamesHumanMoveData = {
    gameId: string;
    requestBody: MoveCreate;
};

export type GamesHumanMoveResponse = (Game);

export type GamesMakeBotMoveData = {
    gameId: string;
};

export type GamesMakeBotMoveResponse = (BotMoveResponse);

export type GamesGetGameHistoryData = {
    gameId: string;
};

export type GamesGetGameHistoryResponse = (Array<Moves>);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type SimulationRunSimulationData = {
    requestBody: SimulationRequest;
};

export type SimulationRunSimulationResponse = (Simulation);

export type SimulationReadSimulationsData = {
    limit?: number;
    skip?: number;
};

export type SimulationReadSimulationsResponse = (SimulationsPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);