"""Añadida propiedad de partida

Revision ID: 4b53e29bc0ee
Revises: 653fcb7cea8e
Create Date: 2025-12-18 13:22:21.848750

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '4b53e29bc0ee'
down_revision = '653fcb7cea8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('owner_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'game', 'user', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'game', type_='foreignkey')
    op.drop_column('game', 'owner_id')
    # ### end Alembic commands ###
