"""Modelo inicial reversi

Revision ID: 653fcb7cea8e
Revises: a92dfaa89b67
Create Date: 2025-12-09 23:16:47.993484

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '653fcb7cea8e'
down_revision = 'a92dfaa89b67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aiconfig',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('algorithm', sa.Enum('RANDOM', 'ALPHABETA', 'MONTECARLO', 'QLEARNING', name='aialgorithm'), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('player_black_id', sa.Uuid(), nullable=True),
    sa.Column('bot_black_id', sa.Uuid(), nullable=True),
    sa.Column('player_white_id', sa.Uuid(), nullable=True),
    sa.Column('bot_white_id', sa.Uuid(), nullable=True),
    sa.Column('board_state', sa.JSON(), nullable=True),
    sa.Column('score_black', sa.Integer(), nullable=False),
    sa.Column('score_white', sa.Integer(), nullable=False),
    sa.Column('current_turn', sa.Enum('BLACK', 'WHITE', name='turn'), nullable=True),
    sa.Column('winner', sa.Enum('BLACK', 'WHITE', 'DRAW', name='winner'), nullable=True),
    sa.ForeignKeyConstraint(['bot_black_id'], ['aiconfig.id'], ),
    sa.ForeignKeyConstraint(['bot_white_id'], ['aiconfig.id'], ),
    sa.ForeignKeyConstraint(['player_black_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['player_white_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('moves',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('game_id', sa.Uuid(), nullable=False),
    sa.Column('move_number', sa.Integer(), nullable=False),
    sa.Column('player', sa.Enum('BLACK', 'WHITE', name='turn'), nullable=True),
    sa.Column('position', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('moves')
    op.drop_table('game')
    op.drop_table('aiconfig')
    # ### end Alembic commands ###
