"""Añadida heuristica a AIConfig

Revision ID: 6f98d0865358
Revises: 8edf7ed6cf52
Create Date: 2026-01-07 21:31:40.335773

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision = "6f98d0865358"
down_revision = "8edf7ed6cf52"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    aiheuristic_enum = sa.Enum(
        "static_weights",
        "mobility_based",
        "hybrid",
        "none",
        name="aiheuristic",
    )

    aiheuristic_enum.create(op.get_bind())

    op.add_column("aiconfig", sa.Column("heuristic", aiheuristic_enum, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("aiconfig", "heuristic")

    aiheuristic_enum = sa.Enum(
        "static_weights",
        "mobility_based",
        "hybrid",
        "none",
        name="aiheuristic",
    )
    aiheuristic_enum.drop(op.get_bind())
    # ### end Alembic commands ###
