"""Añadidas medidas tiempo y memoria

Revision ID: 79fbfcb86453
Revises: 6f98d0865358
Create Date: 2026-02-10 21:11:04.203896

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '79fbfcb86453'
down_revision = '6f98d0865358'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('moves', sa.Column('execution_time', sa.Float(), nullable=True))
    op.add_column('moves', sa.Column('memory_used', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('moves', 'memory_used')
    op.drop_column('moves', 'execution_time')
    # ### end Alembic commands ###
