"""Añadida relación simulación partida

Revision ID: 80b94d5586fe
Revises: 79fbfcb86453
Create Date: 2026-02-10 22:10:42.891893

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '80b94d5586fe'
down_revision = '79fbfcb86453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('simulation_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'game', 'simulation', ['simulation_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'game', type_='foreignkey')
    op.drop_column('game', 'simulation_id')
    # ### end Alembic commands ###
