"""simulaciones

Revision ID: 8edf7ed6cf52
Revises: 4b53e29bc0ee
Create Date: 2026-01-06 20:25:28.518330

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '8edf7ed6cf52'
down_revision = '4b53e29bc0ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simulation',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('num_games', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('bot_black_id', sa.Uuid(), nullable=False),
    sa.Column('bot_white_id', sa.Uuid(), nullable=False),
    sa.Column('black_wins', sa.Integer(), nullable=False),
    sa.Column('white_wins', sa.Integer(), nullable=False),
    sa.Column('draws', sa.Integer(), nullable=False),
    sa.Column('time_elapsed', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['bot_black_id'], ['aiconfig.id'], ),
    sa.ForeignKeyConstraint(['bot_white_id'], ['aiconfig.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('simulation')
    # ### end Alembic commands ###
